### ISSUE TITLE
When should sentencepieces be used?

### ISSUE THREAD

**Issue by Yuran-Zhao** [NLP2CT/Meta-Curriculum#2]
Hi, according to the paper, "the corpus is encoded with sentencepieces (Kudo and Richardson 2018) using 40k joint dictionary." 
But it seems that a spm-model is not needed before step 5 preparing meta-learning data. So I wonder when should I train this model? 
I only realize that you used subword-nmt in the pre-process of lm_train, but still not knowing when to use sentencepieces.

**Comment by Ririkoo** [comment]
Hi Yuran,

For the LM-related parts, the subword-nmt is utilized to train the LM then get the scores. Please note that it will not significantly affect the subsequent procedure since we only get the scores in this step.

The meta-learning part only relies on the scores given by LM, but uses the sentencepieces as the encoding method. See this [file](https://github.com/NLP2CT/Meta-Curriculum/blob/16e40d8fb3382b7ddbc656a474aa1bd9c882561f/meta_data_prep.py#L114).

Thanks for your issue. I deem that it would achieve better results if we also use the sentencepieces in the LM part.

Sorry for the confusing part.

**Comment by Ririkoo** [comment]
> Hi, according to the paper, "the corpus is encoded with sentencepieces (Kudo and Richardson 2018) using 40k joint dictionary."
> But it seems that a spm-model is not needed before step 5 preparing meta-learning data. So I wonder when should I train this model?
> I only realize that you used subword-nmt in the pre-process of lm_train, but still not knowing when to use sentencepieces.

Hi Yuran,

For the LM-related parts, the subword-nmt is utilized to train the LM. Please note that it will not significantly affect the subsequent procedure since we only use the trained LM to  get the scores.

The meta-learning part only relies on the scores given by LM, but uses the sentencepieces as the encoding method. See this [file](https://github.com/NLP2CT/Meta-Curriculum/blob/16e40d8fb3382b7ddbc656a474aa1bd9c882561f/meta_data_prep.py#L114).

Thanks for your issue. I deem that it would achieve better results if we also use the sentencepieces in the LM part.

Sorry for the confusing part.

**Comment by Yuran-Zhao** [comment]
Thanks for your quick reply. I get it :D
Btw, which type did you use to train the spm-model, `--model_type=bpe` or `--model_type=unigram`?

**Comment by Ririkoo** [comment]
Hi Yuran,

I used the default method when I was working on this paper, i.e., `unigram` .

Here is the script piece I used last year (maybe outdated):

```bash 
spm_train --bos_id=-1 --eos_id=0 --unk_id=1 \
    --vocab_size 40000 --input train.all \
    --shuffle_input_sentence true \
    --model_prefix joint.40k
```

Tips: Since the merged training corpus may be large, you can try adjust `--input_sentence_size ` according to your computational infrastructure.

**Comment by Ririkoo** [comment]
> Thanks for your quick reply. I get it :D
> Btw, which type did you use to train the spm-model, `--model_type=bpe` or `--model_type=unigram`?

Hi Yuran,

I used the default method when I was working on this paper, i.e., `unigram` .

Here is the script piece I used last year (maybe outdated):

```bash 
spm_train --bos_id=-1 --eos_id=0 --unk_id=1 \
    --vocab_size 40000 --input train.all \
    --shuffle_input_sentence true \
    --model_prefix joint.40k
```

Tips: Since the merged training corpus may be large, you may adjust `--input_sentence_size ` according to your computational infrastructure.

**Comment by Yuran-Zhao** [comment]
Thanks a lot for your tips and patience!
